### ISSUE TITLE
Show preview before upload

### ISSUE THREAD

**Issue by kamov** [ajgarn/CanvasImageUploader#2]
Hi,
I am looking to just show preview of many images before upload.
Using filereader browser become slow and can't handle more than 50 images.
I guess if possible with this plugin handle many images to show preview, then uploading is handle by me.
thanks

**Comment by ajgarn** [comment]
Sure, currently the uploader only supports to hold data about one image at a time, but if you just want the preview functionality you could easily extend the example given in the file [example.html](https://github.com/ajgarn/CanvasImageUploader/blob/master/example.html). Check out the function `onImageChanged(e)`. Instead of copying to a single preview canvas in `copyToCanvas()`, create a new canvas element and insert it to your DOM.

**Comment by kamov** [comment]
Thanks, I will try.
